# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      # - name: Build
      #   run: go build -v ./...

      - name: Benchmark
        run: go test -bench=. -benchtime=1000x -benchmem ./test/benchmark/...

      - name: Test
        run: go test -v ./test/unit/...
